export const ActionTypes = {
    SET_BANNER: "SET_BANNER",
    SET_OFFERS: "SET_OFFERS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_DEVELOPERS: "SET_DEVELOPERS",
    SET_CATEGORIES: "SET_CATEGORIES",
    SET_STORES: "SET_STORES",
};